### ISSUE TITLE
[madvoc] problems about 'AutomagicMadvocConfigurator'

### ISSUE THREAD

**Issue by zqq90** [oblac/jodd#157]
When upgrade to 3.6, some problems occur,
As usual, config `AutomagicMadvocConfigurator` in `madvoc.props`,
For some reason, some third party jars put struts and jodd supports in one jar, and we should excluded
supports for others

```
[automagicMadvocConfigurator]
includedEntries= jodd.*, my.company.support.jodd.*
ignoreException= true
```
1. `includedEntries` don't works well, since i figure out that, `InExRules` use _blacklist_ mode as default. but no way to change this mode in the `madvoc.props`
2. Then i try `ignoreException`, unfortunately, this  don't works too when `ClassLoaderUtil.loadClass(className)` with a `NoClassDefFoundError: org/apache/.../StrutsResultSupport`.

finally, fixed by

```
excludedEntries=my.company.support.struts2.*,my.company.support.[etc..].*,
```
